# NumPy Tutorial
<참고 자료>  
NumPy: the absolute basics for beginners [link](https://numpy.org/doc/stable/user/absolute_beginners.html#reading-the-example-code)

### Welcome to NumPy!
- NumPy (Numerical Python)
- 오픈 소스 파이썬 라이브러리
- 과학 및 엔지니어링 분야에서 사용
- 수치 데이터를 처리하기 위한 보편적인 표준
- 과학 / 산업 연구자, 개발자들이 사용중
- Pandas, SciPy, Matplotlib, scikit-learn 등 다양한 파이썬 패키지에서 광범위하게 사용
- 다차원 배열 및 행렬 데이터 구조를 다룸
- homogeneous n-차원 배열 객체인 ndarray에 대하여 효율적인 연산을 수행
- 다양한 수학적 연산이 수행 가능함

### Installing NumPy


```
conda install numpy
```
or
```
pip install numpy
```

### How to import NumPy


In [1]:
import numpy as np

### What’s the difference between a Python list and a NumPy array?
- 리스트는 하나의 리스트 안에 여러 종류의 자료형을 포함할 수 있음
- 넘파이 배열의 모든 요소는 동질적 (homogeneous) 이어야 함 
- 그렇기 때문에 넘파이 배열이 수행하는 수학적 연산은 극도로 효율적임
- 넘파이 배열은 리스트 보다 빠르고 컴팩트 함
- 메모리 소모가 적고 최적화 되어 있음

### What is an array?

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
print(a[0], type(a[0]), type(a))

[1 2 3 4] <class 'numpy.ndarray'> <class 'numpy.ndarray'>


- 1D array -> 벡터
- 2D array -> 행렬
- 3D or higher dimension array -> 텐서
- 넘파이에서 차원은 axes라고 부름

### How to create a basic array


In [5]:
a = np.array([1, 2, 3])

앞서 말한것 처럼 1D array는 벡터처럼 생각한다

<img src="numpy_imgs/basic_array.png">

요소가 모두 0인 배열 만들기

In [6]:
np.zeros(2)

array([0., 0.])

요소가 모두 1인 배열 만들기

In [7]:
np.ones(2)

array([1., 1.])

요소를 랜덤하게 채우는 배열만들기
- empty array는 초기값이 랜덤하고 메모리 상태에 따라 달라짐 (속도 때문에 zeros 보다 많이 사용된다고 함)

In [8]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

범위형 배열 만들기

In [9]:
np.arange(4)

array([0, 1, 2, 3])

In [10]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

동일 간격으로 범위형 배열 만들기

In [11]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

배열의 데이터 타입 지정하기

In [12]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

### Adding, removing, and sorting elements


In [13]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

배열 정렬하기

In [14]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

배열 합치기

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [16]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

0-axis 기준으로 배열 합치기

In [17]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [18]:
x.shape, y.shape

((2, 2), (1, 2))

In [19]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### How do you know the shape and size of an array?


In [20]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [21]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

배열의 차원 확인하기

In [22]:
array_example.ndim

3

배열의 size 확인하기 (요소의 갯수)

In [23]:
array_example.size

24

배열의 shape 확인하기

In [24]:
array_example.shape

(3, 2, 4)

### Can you reshape an array?


In [25]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


배열의 shape 변경하기

In [26]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


### How to convert a 1D array into a 2D array (how to add a new axis to an array)


In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

새로운 차원 추가하기 - 방법1

In [28]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [29]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [30]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [31]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

새로운 차원 추가하기 - 방법2

In [32]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [33]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

### Indexing and slicing


In [34]:
data = np.array([1, 2, 3])

In [35]:
data[1]

2

In [36]:
data[0:2]

array([1, 2])

In [37]:
data[1:]

array([2, 3])

In [38]:
data[-2:]

array([2, 3])

<img src="numpy_imgs/indexing_slicing.png">

불 자료형을 이용한 인덱싱과 슬라이싱

In [39]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [40]:
print(a[a < 5])

[1 2 3 4]


In [41]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [42]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [43]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [44]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [45]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [46]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [47]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [48]:
print(a[b])

[1 2 3 4]


In [49]:
a[0, [0,1,2,3]], a[[0], [0,1,2,3]]

(array([1, 2, 3, 4]), array([1, 2, 3, 4]))

In [50]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


### How to create an array from existing data


In [51]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [53]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

두 배열을 세로로 붙이기

In [54]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

두 배열을 가로로 붙이기

In [55]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

깊은 복사와 얕은 복사

In [56]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [57]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [58]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [59]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
b2 = a[0, :].copy()
b2

array([99,  2,  3,  4])

In [61]:
b2[0] = 1
b2

array([1, 2, 3, 4])

In [62]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array operations


<img src="numpy_imgs/basic_array_operations_1.png">

In [63]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

<img src="numpy_imgs/basic_array_operations_2.png">

In [64]:
data - ones

array([0, 1])

<img src="numpy_imgs/basic_array_operations_3.png">

In [65]:
data * data

array([1, 4])

<img src="numpy_imgs/basic_array_operations_4.png">

In [66]:
data / data

array([1., 1.])

<img src="numpy_imgs/basic_array_operations_5.png">

### Broadcasting


In [71]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

<img src="numpy_imgs/broadcasting.png">

[Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)

### More useful array operations


In [72]:
data.max()

2.0

<img src="numpy_imgs/max.png">

In [73]:
data.min()

1.0

<img src="numpy_imgs/min.png">

In [74]:
data.sum()

3.0

<img src="numpy_imgs/sum.png">

In [75]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [76]:
a.sum()

4.8595784

In [77]:
a.min()

0.05093587

In [78]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [79]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

### Creating matrices


In [80]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

<img src="numpy_imgs/create_matrix.png">

In [81]:
data[0, 1]

2

In [82]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [83]:
data[0:2, 0]

array([1, 3])

<img src="numpy_imgs/matrix_indexing_slicing.png">

In [84]:
data.max()

6

In [85]:
data.min()

1

In [86]:
data.sum()

21

<img src="numpy_imgs/matrix_max_min_sum.png">

In [87]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [88]:
data.max(axis=0)

array([5, 6])

<img src="numpy_imgs/matrix_max_axis_0.png">

In [89]:
data.max(axis=1)

array([2, 5, 6])

<img src="numpy_imgs/matrix_max_axis_1.png">

In [90]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

<img src="numpy_imgs/data_plus_ones.png">

In [91]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

<img src="numpy_imgs/data_plus_ones_row.png">

In [92]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [93]:
np.ones(3)

array([1., 1., 1.])

<img src="numpy_imgs/np_ones.png">

In [94]:
np.zeros(3)

array([0., 0., 0.])

<img src="numpy_imgs/np_zeros.png">

In [95]:
np.random.random(3)

array([0.49087189, 0.34888197, 0.28064706])

<img src="numpy_imgs/np_random.png">

In [96]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<img src="numpy_imgs/np_ones_2dim.png">

In [97]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

<img src="numpy_imgs/np_zeros_2dim.png">

In [98]:
np.random.random((3,2))

array([[0.05233766, 0.90184468],
       [0.38915378, 0.90946062],
       [0.82968804, 0.27270138]])

<img src="numpy_imgs/np_random_2dim.png">

### Generating random numbers


In [99]:
np.random.randint(0, 5 + 1, size=(2,4))

array([[3, 3, 4, 2],
       [0, 4, 0, 5]])

### How to get unique items and counts


In [100]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [101]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [102]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [103]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [104]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [105]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [106]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [107]:
unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True
)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [108]:
indices

array([0, 1, 2], dtype=int64)

In [136]:
occurrence_count

array([2, 1, 1], dtype=int64)

### Transposing and reshaping a matrix


In [109]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

<img src="numpy_imgs/reshape.png">

In [111]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [112]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [113]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

<img src="numpy_imgs/data_t.png">

### How to reverse an array


In [114]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [115]:
reversed_arr = np.flip(arr)

In [116]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [138]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [139]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [142]:
np.flip(arr_2d.T).T

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [119]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [120]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


### Reshaping and flattening multidimensional arrays


In [123]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [124]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [125]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [126]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [127]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [128]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]


### How to save and load NumPy objects


In [129]:
a = np.array([1, 2, 3, 4, 5, 6])

In [130]:
np.save('data/filename.npy', a)

In [131]:
b = np.load('data/filename.npy')

In [132]:
print(b)

[1 2 3 4 5 6]


In [133]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
np.savetxt('data/new_file.csv', csv_arr)

In [135]:
np.loadtxt('data/new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])