### 파이썬으로 할 수 있는 일
- 데이터 분석 (tensorflow, pytorch)
- 인공지능 딥러닝
- 웹 프로그래밍 (백 엔드 등)
- 수치연산 (C언어가 더욱 좋다, numpy 가 C로 구성 되어 있다.)
- DB 프로그래밍
- 시스템 유틸리티
- 사물 인터넷 (IOT)

### 파이썬 에 적합하지 않은 일
- 시스템 밀접한 영역
- 모바일 프로그래밍

### 스네이크 케이스와, 캐멀 케이스
- 변수 명 지정할 때 이용한다.
    - 스네이크 케이스: 언더바 이용, 파이썬 에서는 보통 **변수** 또는 **함수명** 지정할 때
        - itemlist → item_list
        - loginstatus → login_status
    - 캐멀 케이스: 대문자 이용, 파이썬 에서는 보통 을 **클래스** 지정할 때
        - itemlist  → ItemList or itemList
        - loginstatus → LoginStatus or loginStatus

In [5]:
# 절차지향: 함수로 자동차 동작 처리
def start_car():
    print("시동을 겁니다.")

def drive_car():
    print("자동차가 달립니다.")

def stop_car():
    print("자동차가 멈춥니다.")

start_car()
drive_car()
stop_car()


시동을 겁니다.
자동차가 달립니다.
자동차가 멈춥니다.


In [6]:
# 객체지향: 자동차 객체 생성 후 동작 처리
class Car:
    def start(self):
        print("시동을 겁니다.")
        
    def drive(self):
        print("자동차가 달립니다.")
        
    def stop(self):
        print("자동차가 멈춥니다.")

my_car = Car()
my_car.start()
my_car.drive()
my_car.stop()


시동을 겁니다.
자동차가 달립니다.
자동차가 멈춥니다.


### 리스트와 배열의 차이
  - | **List** | **Array** |
    | --- | --- |
    | 여러 데이터 타입이 동시에 들어있을 수 있다. | 한종류의 데이터 타입만 가능하다 |
    | 추가적인 외부 모듈이 필요 없다. | 배열의 추가적인 모듈이 필요하다. |
    | 직접적인 수학 계산이 불가능하다. | 직접적인 수학 계산이 가능하다. |
    | 짧은 시퀀스 데이터에 유리하다. | 긴 시퀀스 데이터에 유리하다 |
    | 추가와 삭제 및 데이터에 유연하다. | 추가와 삭제 및 데이터에 유연하지 않다. |
    | 메모리 차지가 크다 | 메모리 차지가 적다 |
    | 배열 안의 각 요소의 길이는 달라도 된다.. | 배열 안의 각 요소의 길이는 모두 같아야 한다. |

In [7]:
# 배열 안의 각 요소의 길이는 모두 같아야 한다

import numpy as np

list_sample = [[1,2,3],[4,5,6],[7,8,9]]
np_array = np.array(list_sample)
print(np_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
list_sample = [[1,2,3],[4,5,6],[7,8,9,10]] #배열 안의 각 요소의 길이는 모두 같아야 한다.
np_array = np.array(list_sample)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.